# Generated by Django 6.0.4 on 2026-04-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hr_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='hr_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='hr_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
