# Generated by Django 6.0.4 on 2026-04-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Vetri Consultancy Services', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_config/')),
                ('login_illustration', models.ImageField(blank=True, null=True, upload_to='site_config/')),
                ('candidate_tab_text', models.CharField(default='Candidate', max_length=50)),
                ('trainee_tab_text', models.CharField(default='Trainee', max_length=50)),
                ('company_tab_text', models.CharField(default='Company', max_length=50)),
            ],
            options={
                'verbose_name': 'Login UI Settings',
                'verbose_name_plural': 'Login UI Settings',
            },
        ),
    ]
