# Generated by Django 6.0.4 on 2026-04-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0002_job_hr_email_job_hr_name_job_hr_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
