# Generated by Django 6.0.4 on 2026-04-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0003_candidateprofile_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason shown to company if rejected', null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
