# Generated by Django 6.0.4 on 2026-04-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0003_skill_candidateprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='is_fresher',
            field=models.BooleanField(default=False),
        ),
    ]
