# Generated by Django 6.0.4 on 2026-04-27 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0004_companyprofile_is_fresher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='is_fresher',
        ),
    ]
