# Generated by Django 6.0.4 on 2026-04-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0004_remove_companyprofile_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='reviewed_at',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
