# Generated by Django 6.0.4 on 2026-04-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0005_remove_companyprofile_approval_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Provide a reason if rejecting the company', null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
