# Generated by Django 6.0.4 on 2026-04-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0005_remove_companyprofile_is_fresher'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='is_fresher',
            field=models.BooleanField(default=False),
        ),
    ]
