# Generated by Django 6.0.4 on 2026-04-29 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0006_remove_companyprofile_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to='vcs.companyprofile'),
        ),
    ]
