# Generated by Django 6.0.4 on 2026-04-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0007_job_company_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='subscription_type',
            field=models.CharField(choices=[('Free', 'Free'), ('Pro', 'Pro')], default='Free', help_text="Candidate's current subscription plan", max_length=10),
        ),
    ]
