# Generated by Django 6.0.4 on 2026-04-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0008_candidateprofile_subscription_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('feed_type', models.CharField(choices=[('article', 'Article'), ('tip', 'Career Tip'), ('news', 'Industry News'), ('announcement', 'Announcement')], default='article', max_length=20)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='feeds/')),
                ('excerpt', models.TextField(help_text='Short summary shown on card', max_length=300)),
                ('content', models.TextField(help_text='Full article content')),
                ('author_name', models.CharField(default='VCS Team', max_length=100)),
                ('tags', models.CharField(blank=True, help_text='Comma separated e.g. Python, Career, Jobs', max_length=255, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-is_featured', '-published_at'],
            },
        ),
    ]
