# Generated by Django 6.0.4 on 2026-04-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0009_feed'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='ELEVATE YOUR CAREER', max_length=100)),
                ('main_title', models.CharField(default='25% Off on Pro', max_length=100)),
                ('button_text', models.CharField(default='Claim your offer', max_length=50)),
                ('bottom_text', models.CharField(default='Limited time only!', max_length=100)),
                ('illustration', models.ImageField(blank=True, help_text='Upload the isometric 3D character image here', null=True, upload_to='offers/')),
                ('bg_gradient_start', models.CharField(default='#ffd97d', help_text='Hex color code (e.g., #ffd97d)', max_length=20)),
                ('bg_gradient_end', models.CharField(default='#fff4d1', help_text='Hex color code (e.g., #fff4d1)', max_length=20)),
                ('is_active', models.BooleanField(default=False, help_text='Turn this on to display the banner to Free users')),
            ],
        ),
    ]
