# Generated by Django 6.0.4 on 2026-04-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0010_subscriptionoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Auto-Apply on Jobs', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this feature from the list')),
                ('order', models.PositiveIntegerField(default=0, help_text='Use numbers (1, 2, 3) to sort the list')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
