# Generated by Django 6.0.4 on 2026-04-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0011_profeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='traineeprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traineeprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='traineeprofile',
            name='is_fresher',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='traineeprofile',
            name='languages_known',
            field=models.CharField(blank=True, help_text='Comma separated, e.g. English, Tamil', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='traineeprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='traineeprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='trainee_photos/'),
        ),
        migrations.AddField(
            model_name='traineeprofile',
            name='profile_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traineeprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='trainee_resumes/'),
        ),
        migrations.AddField(
            model_name='traineeprofile',
            name='resume_headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='traineeprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='trainees', to='vcs.skill'),
        ),
    ]
