# Generated by Django 6.0.4 on 2026-04-30 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0012_traineeprofile_date_of_birth_traineeprofile_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='feed',
            name='media_file',
            field=models.FileField(blank=True, help_text='Upload an image or a short video clip', null=True, upload_to='feeds/media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'mp4', 'webm', 'mov'])]),
        ),
    ]
