# Generated by Django 6.0.4 on 2026-04-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0013_remove_feed_thumbnail_feed_media_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.PositiveIntegerField(help_text='Duration in months (e.g., 1, 3, 6)')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='The original full price before any discounts', max_digits=10)),
                ('disc1_pct', models.PositiveIntegerField(default=0, help_text='First discount percentage (e.g., 33). Enter 0 if none.')),
                ('disc1_code', models.CharField(blank=True, help_text='Code name for 1st discount (e.g., 3MOFF)', max_length=50)),
                ('disc2_pct', models.PositiveIntegerField(default=0, help_text='Second discount percentage (e.g., 30). Enter 0 if none.')),
                ('disc2_code', models.CharField(blank=True, help_text='Code name for 2nd discount (e.g., PROSALE30)', max_length=50)),
                ('gst_pct', models.PositiveIntegerField(default=18, help_text='GST Percentage (default is 18%)')),
                ('is_popular', models.BooleanField(default=False, help_text="Highlight this plan with a 'Popular' badge?")),
                ('daily_text', models.CharField(blank=True, help_text="Optional bottom text (e.g., 'just ₹ 20/day')", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this plan from users')),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['months'],
            },
        ),
    ]
