# Generated by Django 6.0.4 on 2026-04-30 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0014_subscriptionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='trainee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='vcs.traineeprofile'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='vcs.candidateprofile'),
        ),
    ]
