# Generated by Django 6.0.4 on 2026-04-30 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0015_jobapplication_trainee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='trainee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='vcs.traineeprofile'),
        ),
        migrations.AddField(
            model_name='employment',
            name='trainee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employments', to='vcs.traineeprofile'),
        ),
        migrations.AddField(
            model_name='project',
            name='trainee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='vcs.traineeprofile'),
        ),
        migrations.AlterField(
            model_name='education',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='vcs.candidateprofile'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employments', to='vcs.candidateprofile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='vcs.candidateprofile'),
        ),
    ]
