# Generated by Django 6.0.4 on 2026-05-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0017_paymentorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_masked_contact',
            field=models.BooleanField(default=True, help_text='Check to partially mask HR contact details and require a button click to reveal.'),
        ),
    ]
