# Generated by Django 6.0.4 on 2026-05-02 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0018_job_is_masked_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['months', 'days'], 'verbose_name': 'Subscription Plan', 'verbose_name_plural': 'Subscription Plans'},
        ),
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='disc1_pct',
            new_name='discount1',
        ),
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='disc1_code',
            new_name='discount1_code',
        ),
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='disc2_pct',
            new_name='discount2',
        ),
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='disc2_code',
            new_name='discount2_code',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='pro_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='days',
            field=models.PositiveIntegerField(default=0, help_text='Duration in days (e.g., 28, 56). Enter 0 if this is a monthly plan.'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vcs.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='months',
            field=models.PositiveIntegerField(default=0, help_text='Duration in months (e.g., 1, 3). Enter 0 if this is a daily plan.'),
        ),
    ]
