# Generated by Django 6.0.4 on 2026-05-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0019_alter_subscriptionplan_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Reviewing', 'Reviewing'), ('Shortlisted', 'Shortlisted'), ('Interview', 'Interview Scheduled'), ('Offered', 'Offer Extended'), ('Rejected', 'Rejected')], default='Applied', max_length=20),
        ),
    ]
