# Generated by Django 6.0.4 on 2026-05-04 10:58

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0020_alter_jobapplication_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Terms and Conditions', max_length=200)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(help_text='You can use HTML here to format paragraphs and lists.')),
                ('role', models.CharField(choices=[('candidate', 'Candidate'), ('company', 'Company')], max_length=20)),
                ('version', models.CharField(help_text='e.g., 1.0, 1.1, 2.0', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Making this active will deactivate previous versions for this role.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Terms & Conditions',
                'verbose_name_plural': 'Terms & Conditions',
                'ordering': ['-created_at'],
            },
        ),
    ]
