# Generated by Django 6.0.4 on 2026-05-04 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0021_termsandconditions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termsandconditions',
            name='version',
        ),
    ]
