# Generated by Django 6.0.4 on 2026-05-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0023_chatbotdocument_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('trainee__isnull', False)), fields=('job', 'trainee'), name='unique_trainee_job_application'),
        ),
    ]
